language: android
dist: trusty
jdk: openjdk-15
android:
  components:
  - tools
  - platform-tools
  - build-tools-30.0.3
  - android-30
  - extra-google-google_play_services
  - $ANDROID_TARGET
  - extra-google-m2repository
  - extra-android-m2repository
